In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from imblearn.under_sampling import RandomUnderSampler

import re

In [ ]:
df = pd.read_csv('/content/avatar_comments_trailer1_full.csv')
df.head()

                                                text
0  I NEED to go see this!!! The 1st 2 movies are ...
1  I can&#39;t wait. I just hope it&#39;s as good...
2                              🙌🙌💯💯🙌💯🌎🌎🌎🌍🌍🌍🌏🌏🌏✔✔✔🖥🖥🖥
3  I can&#39;t tell if Neytiri is either talking ...
4  this reminds me of genshin impact in some way,...

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    if not isinstance(text, str):
        return ""
    # 3. Remove HTML tags & entities
    text = BeautifulSoup(text, "html.parser").get_text()
    # 4. Remove non-English characters (non ASCII)
    text = text.encode("ascii", "ignore").decode()
    # 5. Clean symbols, numbers, and punctuation
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(f"[{re.escape(string.punctuation)}]", "", text) # Remove punctuation
    text = re.sub(r"\d+", "", text) # Remove numbers
    text = re.sub(r"[^a-z\s]", "", text) # Keep only letters and spaces
    text = re.sub(r"\s+", " ", text).strip()
    # 6. Remove stopwords and 7. Lemmatization
    text = " ".join([lemmatizer.lemmatize(word) for word in text.split() if word not in stop_words])
    return text

# Apply preprocessing to the 'text' column and create 'clean_text'
df['clean_text'] = df['text'].apply(preprocess_text)

# 2. Drop duplicates and missing values based on 'clean_text'
df.drop_duplicates(inplace=True)
df.dropna(subset=['clean_text'], inplace=True)

# 8. Filter out short texts
df = df[df['clean_text'].str.count(' ') >= 2]

df.head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,text,clean_text
0,I NEED to go see this!!! The 1st 2 movies are ...,need go see st movie definitely among favorite...
1,I can&#39;t wait. I just hope it&#39;s as good...,cant wait hope good first two took year get do...
3,I can&#39;t tell if Neytiri is either talking ...,cant tell neytiri either talking jake spider last
4,"this reminds me of genshin impact in some way,...",reminds genshin impact way cannot wait watch b...
6,The only thing that interests me is the music....,thing interest music dont care rest

In [ ]:
from nltk.sentiment import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')
sia = SentimentIntensityAnalyzer()

def get_sentiment(text):
    score = sia.polarity_scores(text)['compound']
    if score > 0.05:
        return 'positive'
    elif score < -0.05:
        return 'negative'
    else:
        return 'neutral'

df['sentiment'] = df['clean_text'].apply(get_sentiment)
df['sentiment'].value_counts()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

sentiment
positive    3939
neutral     3015
negative    2763
Name: count, dtype: int64

In [5]:

df = pd.read_csv('/content/avatar_comments_trailer_clean.csv',
                 sep=None, engine='python', on_bad_lines='skip')

# Bersihkan kolom
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df.columns = df.columns.str.replace(';', '').str.replace(',', '').str.strip()

if 'sentiment' in df.columns:
    df['sentiment'] = df['sentiment'].astype(str).str.replace(';', '').str.strip()

# Aplikasikan pembersihan teks yang lebih baik
df['processed_text'] = df['text'].apply(advanced_text_cleaning)

# Hapus teks kosong atau terlalu pendek
df = df[df['processed_text'].str.len() > 5].reset_index(drop=True)

print(f"Dataset size after cleaning: {len(df)}")
print(f"Sentiment distribution:\n{df['sentiment'].value_counts()}")

Dataset size after cleaning: 12716
Sentiment distribution:
sentiment
positive    5139
neutral     3914
negative    3663
Name: count, dtype: int64

In [6]:
# ========================================
# 3. BALANCED SAMPLING
# ========================================
rus = RandomUnderSampler(sampling_strategy='auto', random_state=42)
X_res, y_res = rus.fit_resample(df[['processed_text']], df['sentiment'])
print(f"\nDistribusi setelah undersampling:\n{y_res.value_counts()}")

Distribusi setelah undersampling:
sentiment
negative    3663
neutral     3663
positive    3663
Name: count, dtype: int64

In [7]:
# 4. LABEL ENCODING
# ========================================
le = LabelEncoder()
y_encoded = le.fit_transform(y_res)
print(f"\nLabel mapping: {dict(zip(le.classes_, le.transform(le.classes_)))}")

Label mapping: {'negative': np.int64(0), 'neutral': np.int64(1), 'positive': np.int64(2)}

In [8]:
# 5. TF-IDF DENGAN PARAMETER OPTIMAL
# ========================================
# Strategi 1: TF-IDF dengan ngram yang lebih luas dan parameter seimbang
tfidf = TfidfVectorizer(
    max_features=8000,
    ngram_range=(1, 4),
    sublinear_tf=True,
    min_df=2,
    max_df=0.85,
    strip_accents='unicode',
    analyzer='word',
    token_pattern=r'\w{1,}',
    use_idf=True,
    smooth_idf=True,
    norm='l2'
)

X_tfidf = tfidf.fit_transform(X_res['processed_text'])
print(f"\nTF-IDF shape: {X_tfidf.shape}")

TF-IDF shape: (10989, 8000)

In [9]:
# ========================================
# 6. SPLIT DATA
# ========================================
X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

#Menggunakan Model Logistic Regression dengan GridSearchCV

In [48]:

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score


lr_base = LogisticRegression(
    max_iter=5000,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1,
    tol=0.0001
)


param_grid = {
    'C': [0.1, 0.01, 0.005, 1.0],
    'penalty': ['l1', 'l2'],
    'solver': ['saga'],
}


grid_search = GridSearchCV(
    estimator=lr_base,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    verbose=1,
    n_jobs=-1
)


grid_search.fit(X_train, y_train)


lr_best_model = grid_search.best_estimator_


y_train_pred_gs = lr_best_model.predict(X_train)
y_test_pred_gs = lr_best_model.predict(X_test)

train_acc_gs = accuracy_score(y_train, y_train_pred_gs)
test_acc_gs = accuracy_score(y_test, y_test_pred_gs)

print(f"✓ Akurasi Train (Model Terbaik): {train_acc_gs*100:.2f}%")
print(f"✓ Akurasi Test (Model Terbaik) : {test_acc_gs*100:.2f}%")

Fitting 5 folds for each of 8 candidates, totalling 40 fits
✓ Akurasi Train (Model Terbaik): 86.34%
✓ Akurasi Test (Model Terbaik) : 86.21%

INFERENSI MODEL LOGISTIC REGRESSION

In [52]:
def predict_sentiment(texts):
    if isinstance(texts, str):
        texts = [texts]
    X_new = tfidf.transform(texts)
    preds = lr_best_model.predict(X_new)
    for text, label in zip(texts, preds):
        print(f"Text: {text}\nSentiment: {label}\n")

test_texts = [
    "I really love this product, it's amazing!",
    "The service was terrible and disappointing."
]

predict_sentiment(test_texts)

Text: I really love this product, it's amazing!
Sentiment: positive

Text: The service was terrible and disappointing.
Sentiment: negative

#Menggunakan Model LightGBM

In [61]:
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, classification_report

model_lgbm = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    num_leaves=32,
    max_depth=-1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model_lgbm.fit(X_train, y_train)

y_train_pred = model_lgbm.predict(X_train)
y_test_pred = model_lgbm.predict(X_test)

train_acc = accuracy_score(y_train, y_train_pred)
test_acc = accuracy_score(y_test, y_test_pred)

print(f"✓ Akurasi Train: {train_acc*100:.2f}%")
print(f"✓ Akurasi Test : {test_acc*100:.2f}%")
print("\nClassification Report:\n")
print(classification_report(y_test, y_test_pred))

========================================
LIGHTGBM MODEL (RINGAN + AKURAT)
========================================
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.083706 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 34422
[LightGBM] [Info] Number of data points in the train set: 8791, number of used features: 1261
[LightGBM] [Info] Start training from score -1.098385
[LightGBM] [Info] Start training from score -1.098726
[LightGBM] [Info] Start training from score -1.098726
✓ Akurasi Train: 94.74%
✓ Akurasi Test : 83.58%

Classification Report:

              precision    recall  f1-score   support

    negative       0.84      0.79      0.82       732
     neutral       0.81      0.89      0.85       733
    positive       0.86      0.82      0.84       733

    accuracy                           0.84      2198
   macro avg       0.84      0.84      0.84      2198
weighted avg       0.84      0.84      0.84      2198

In [64]:
#INFERENSI MODEL
def predict_sentiment(texts):
    X_new = tfidf.transform(texts)
    preds = model_lgbm.predict(X_new)
    for t, p in zip(texts, preds):
        print(f"{t} → {p}")

test_texts = [
    "this movie was amazing and touching",
    "the plot was boring and predictable",
    "it was okay"
]

predict_sentiment(test_texts)

this movie was amazing and touching → positive
the plot was boring and predictable → negative
it was okay → neutral

In [65]:
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense, Dropout
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report


df = pd.read_csv('/content/avatar_comments_trailer_clean.csv')
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df.columns = df.columns.str.strip()

texts = df['text'].astype(str).tolist()
labels = df['sentiment'].astype(str)

In [66]:
# Encode label
le = LabelEncoder()
y = le.fit_transform(labels)

# Tokenisasi teks
tokenizer = Tokenizer(num_words=10000, oov_token="<OOV>")
tokenizer.fit_on_texts(texts)

# Konversi ke urutan angka
X = tokenizer.texts_to_sequences(texts)
X = pad_sequences(X, maxlen=100)  # potong/panjang jadi 100 token

In [68]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

In [69]:
model = Sequential([
    Embedding(input_dim=10000, output_dim=64, input_length=100),
    GRU(64, dropout=0.2, recurrent_dropout=0.2),
    Dense(32, activation='relu'),
    Dropout(0.3),
    Dense(len(le.classes_), activation='softmax')
])

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [70]:
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=6,
    batch_size=64,
    verbose=1
)

Epoch 1/6
140/140 ━━━━━━━━━━━━━━━━━━━━ 26s 152ms/step - accuracy: 0.4874 - loss: 0.9997 - val_accuracy: 0.7248 - val_loss: 0.6383
Epoch 2/6
140/140 ━━━━━━━━━━━━━━━━━━━━ 19s 139ms/step - accuracy: 0.8008 - loss: 0.5179 - val_accuracy: 0.8024 - val_loss: 0.5032
Epoch 3/6
140/140 ━━━━━━━━━━━━━━━━━━━━ 23s 158ms/step - accuracy: 0.8966 - loss: 0.3109 - val_accuracy: 0.8173 - val_loss: 0.4788
Epoch 4/6
140/140 ━━━━━━━━━━━━━━━━━━━━ 20s 145ms/step - accuracy: 0.9343 - loss: 0.2153 - val_accuracy: 0.8231 - val_loss: 0.5112
Epoch 5/6
140/140 ━━━━━━━━━━━━━━━━━━━━ 20s 142ms/step - accuracy: 0.9509 - loss: 0.1667 - val_accuracy: 0.8318 - val_loss: 0.5218
Epoch 6/6
140/140 ━━━━━━━━━━━━━━━━━━━━ 21s 150ms/step - accuracy: 0.9591 - loss: 0.1378 - val_accuracy: 0.8239 - val_loss: 0.5890

In [71]:
# EVALUASI MODEL
y_train_pred = np.argmax(model.predict(X_train), axis=1)
y_test_pred = np.argmax(model.predict(X_test), axis=1)

# Hitung akurasi
train_acc = accuracy_score(y_train, y_train_pred)
test_acc = accuracy_score(y_test, y_test_pred)

# Tampilkan hasil

print("EVALUASI MODEL GRU")
print(f"✓ Akurasi Train : {train_acc*100:.2f}%")
print(f"✓ Akurasi Test  : {test_acc*100:.2f}%")

279/279 ━━━━━━━━━━━━━━━━━━━━ 6s 19ms/step
120/120 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step
EVALUASI MODEL GRU
✓ Akurasi Train : 97.53%
✓ Akurasi Test  : 82.39%

In [72]:
#INFERENSI MODEL
def predict_sentiment(texts):
    seq = tokenizer.texts_to_sequences(texts)
    pad = pad_sequences(seq, maxlen=100)
    preds = np.argmax(model.predict(pad), axis=1)
    for t, p in zip(texts, preds):
        print(f"{t} → {le.inverse_transform([p])[0]}")

# Contoh pengujian
test_texts = [
    "this movie is absolutely wonderful",
    "it was boring and too long",
    "just an average film"
]
predict_sentiment(test_texts)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
this movie is absolutely wonderful → positive
it was boring and too long → negative
just an average film → neutral

In [73]:
 pip freeze requirements.txt

absl-py==1.4.0
absolufy-imports==0.3.1
accelerate==1.11.0
aiofiles==24.1.0
aiohappyeyeballs==2.6.1
aiohttp==3.13.1
aiosignal==1.4.0
alabaster==1.0.0
albucore==0.0.24
albumentations==2.0.8
ale-py==0.11.2
alembic==1.17.0
altair==5.5.0
annotated-doc==0.0.3
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.11.0
anywidget==0.9.18
argon2-cffi==25.1.0
argon2-cffi-bindings==25.1.0
array_record==0.8.1
arrow==1.4.0
arviz==0.22.0
astropy==7.1.1
astropy-iers-data==0.2025.10.20.0.39.8
astunparse==1.6.3
atpublic==5.1
attrs==25.4.0
audioread==3.0.1
Authlib==1.6.5
autograd==1.8.0
babel==2.17.0
backcall==0.2.0
beartype==0.22.3
beautifulsoup4==4.13.5
betterproto==2.0.0b6
bigframes==2.26.0
bigquery-magics==0.10.3
bleach==6.2.0
blinker==1.9.0
blis==1.3.0
blobfile==3.1.0
blosc2==3.10.2
bokeh==3.7.3
Bottleneck==1.4.2
bqplot==0.12.45
branca==0.8.2
Brotli==1.1.0
build==1.3.0
CacheControl==0.14.3
cachetools==5.5.2
catalogue==2.0.10
certifi==2025.10.5
cffi==2.0.0
chardet==5.2.0
charset-normalizer==3.4.4
chex==0.1.90
clarabel==0.11.1
click==8.3.0
cloudpathlib==0.23.0
cloudpickle==3.1.1
cmake==3.31.6
cmdstanpy==1.3.0
colorcet==3.1.0
colorlover==0.3.0
colour==0.1.5
community==1.0.0b1
confection==0.1.5
cons==0.4.7
contourpy==1.3.3
cramjam==2.11.0
cryptography==43.0.3
cuda-python==12.6.2.post1
cudf-cu12 @ https://pypi.nvidia.com/cudf-cu12/cudf_cu12-25.6.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
cudf-polars-cu12==25.6.0
cufflinks==0.17.3
cuml-cu12==25.6.0
cupy-cuda12x==13.3.0
curl_cffi==0.13.0
cuvs-cu12==25.6.1
cvxopt==1.3.2
cvxpy==1.6.7
cycler==0.12.1
cyipopt==1.5.0
cymem==2.0.11
Cython==3.0.12
dask==2025.5.0
dask-cuda==25.6.0
dask-cudf-cu12==25.6.0
dataproc-spark-connect==0.8.3
datasets==4.0.0
db-dtypes==1.4.3
dbus-python==1.2.18
debugpy==1.8.15
decorator==4.4.2
defusedxml==0.7.1
diffusers==0.35.2
dill==0.3.8
distributed==2025.5.0
distributed-ucxx-cu12==0.44.0
distro==1.9.0
dlib==19.24.6
dm-tree==0.1.9
docstring_parser==0.17.0
docutils==0.21.2
dopamine_rl==4.1.2
duckdb==1.3.2
earthengine-api==1.5.24
easydict==1.13
editdistance==0.8.1
eerepr==0.1.2
einops==0.8.1
en_core_web_sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl#sha256=1932429db727d4bff3deed6b34cfc05df17794f4a52eeb26cf8928f7c1a0fb85
entrypoints==0.4
et_xmlfile==2.0.0
etils==1.13.0
etuples==0.3.10
Farama-Notifications==0.0.4
fastai==2.8.4
fastapi==0.120.0
fastcore==1.8.13
fastdownload==0.0.7
fastjsonschema==2.21.2
fastprogress==1.0.3
fastrlock==0.8.3
fasttransform==0.0.2
ffmpy==0.6.4
filelock==3.20.0
firebase-admin==6.9.0
Flask==3.1.2
flatbuffers==25.9.23
flax==0.10.7
folium==0.20.0
fonttools==4.60.1
fqdn==1.5.1
frozendict==2.4.6
frozenlist==1.8.0
fsspec==2025.3.0
future==1.0.0
gast==0.6.0
gcsfs==2025.3.0
GDAL==3.8.4
gdown==5.2.0
geemap==0.35.3
geocoder==1.38.1
geographiclib==2.1
geopandas==1.1.1
geopy==2.4.1
gin-config==0.5.0
gitdb==4.0.12
GitPython==3.1.45
glob2==0.7
google==2.0.3
google-adk==1.17.0
google-ai-generativelanguage==0.6.15
google-api-core==2.27.0
google-api-python-client==2.185.0
google-auth==2.38.0
google-auth-httplib2==0.2.0
google-auth-oauthlib==1.2.2
google-cloud-aiplatform==1.122.0
google-cloud-appengine-logging==1.7.0
google-cloud-audit-log==0.4.0
google-cloud-bigquery==3.38.0
google-cloud-bigquery-connection==1.19.0
google-cloud-bigquery-storage==2.33.1
google-cloud-bigtable==2.34.0
google-cloud-core==2.4.3
google-cloud-dataproc==5.23.0
google-cloud-datastore==2.21.0
google-cloud-discoveryengine==0.13.12
google-cloud-firestore==2.21.0
google-cloud-functions==1.21.0
google-cloud-language==2.18.0
google-cloud-logging==3.12.1
google-cloud-monitoring==2.28.0
google-cloud-resource-manager==1.15.0
google-cloud-secret-manager==2.25.0
google-cloud-spanner==3.59.0
google-cloud-speech==2.34.0
google-cloud-storage==2.19.0
google-cloud-trace==1.17.0
google-cloud-translate==3.22.0
google-colab @ file:///colabtools/dist/google_colab-1.0.0.tar.gz
google-crc32c==1.7.1
google-genai==1.46.0
google-generativeai==0.8.5
google-pasta==0.2.0
google-resumable-media==2.7.2
googleapis-common-protos==1.71.0
googledrivedownloader==1.1.0
gradio==5.49.1
gradio_client==1.13.3
graphviz==0.21
greenlet==3.2.4
groovy==0.1.2
grpc-google-iam-v1==0.14.3
grpc-interceptor==0.15.4
grpcio==1.76.0
grpcio-status==1.71.2
grpclib==0.4.8
gspread==6.2.1
gspread-dataframe==4.0.0
gym==0.25.2
gym-notices==0.1.0
gymnasium==1.2.1
h11==0.16.0
h2==4.3.0
h5netcdf==1.7.3
h5py==3.15.1
hdbscan==0.8.40
hf-xet==1.2.0
hf_transfer==0.1.9
highspy==1.11.0
holidays==0.83
holoviews==1.21.0
hpack==4.1.0
html5lib==1.1
httpcore==1.0.9
httpimport==1.4.1
httplib2==0.31.0
httpx==0.28.1
httpx-sse==0.4.3
huggingface-hub==0.36.0
humanize==4.14.0
hyperframe==6.1.0
hyperopt==0.2.7
ibis-framework==9.5.0
idna==3.11
imageio==2.37.0
imageio-ffmpeg==0.6.0
imagesize==1.4.1
imbalanced-learn==0.14.0
immutabledict==4.2.2
importlib_metadata==8.7.0
importlib_resources==6.5.2
imutils==0.5.4
inflect==7.5.0
iniconfig==2.3.0
intel-cmplr-lib-ur==2025.3.0
intel-openmp==2025.3.0
ipyevents==2.0.4
ipyfilechooser==0.6.0
ipykernel==6.17.1
ipyleaflet==0.20.0
ipyparallel==8.8.0
ipython==7.34.0
ipython-genutils==0.2.0
ipython-sql==0.5.0
ipytree==0.2.2
ipywidgets==7.7.1
isoduration==20.11.0
itsdangerous==2.2.0
jaraco.classes==3.4.0
jaraco.context==6.0.1
jaraco.functools==4.3.0
jax==0.7.2
jax-cuda12-pjrt==0.7.2
jax-cuda12-plugin==0.7.2
jaxlib==0.7.2
jeepney==0.9.0
jieba==0.42.1
Jinja2==3.1.6
jiter==0.11.1
joblib==1.5.2
jsonpatch==1.33
jsonpickle==4.1.1
jsonpointer==3.0.0
jsonschema==4.25.1
jsonschema-specifications==2025.9.1
jupyter-console==6.6.3
jupyter-events==0.12.0
jupyter-leaflet==0.20.0
jupyter_client==7.4.9
jupyter_core==5.9.1
jupyter_kernel_gateway @ git+https://github.com/googlecolab/kernel_gateway@b134e9945df25c2dcb98ade9129399be10788671
jupyter_server==2.14.0
jupyter_server_terminals==0.5.3
jupyterlab_pygments==0.3.0
jupyterlab_widgets==3.0.15
jupytext==1.17.3
kaggle==1.7.4.5
kagglehub==0.3.13
keras==3.10.0
keras-hub==0.21.1
keras-nlp==0.21.1
keyring==25.6.0
keyrings.google-artifactregistry-auth==1.1.2
kiwisolver==1.4.9
langchain==0.3.27
langchain-core==0.3.79
langchain-text-splitters==0.3.11
langcodes==3.5.0
langsmith==0.4.38
language_data==1.3.0
lark==1.3.0
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lazy_loader==0.4
libclang==18.1.1
libcudf-cu12 @ https://pypi.nvidia.com/libcudf-cu12/libcudf_cu12-25.6.0-py3-none-manylinux_2_28_x86_64.whl
libcugraph-cu12==25.6.0
libcuml-cu12==25.6.0
libcuvs-cu12==25.6.1
libkvikio-cu12==25.6.0
libpysal==4.13.0
libraft-cu12==25.6.0
librmm-cu12==25.6.0
librosa==0.11.0
libucx-cu12==1.18.1
libucxx-cu12==0.44.0
lightgbm @ file:///tmp/lightgbm/LightGBM/dist/lightgbm-4.6.0-py3-none-linux_x86_64.whl
linkify-it-py==2.0.3
llvmlite==0.43.0
locket==1.0.0
logical-unification==0.4.7
lxml==5.4.0
Mako==1.3.10
marisa-trie==1.3.1
Markdown==3.9
markdown-it-py==4.0.0
MarkupSafe==3.0.3
matplotlib==3.10.0
matplotlib-inline==0.2.1
matplotlib-venn==1.1.2
mcp==1.19.0
mdit-py-plugins==0.5.0
mdurl==0.1.2
miniKanren==1.0.5
missingno==0.5.2
mistune==3.1.4
mizani==0.13.5
mkl==2025.2.0
ml_dtypes==0.5.3
mlxtend==0.23.4
more-itertools==10.8.0
moviepy==1.0.3
mpmath==1.3.0
msgpack==1.1.2
multidict==6.7.0
multipledispatch==1.0.0
multiprocess==0.70.16
multitasking==0.0.12
murmurhash==1.0.13
music21==9.3.0
namex==0.1.0
narwhals==2.9.0
natsort==8.4.0
nbclassic==1.3.3
nbclient==0.10.2
nbconvert==7.16.6
nbformat==5.10.4
ndindex==1.10.0
nest-asyncio==1.6.0
networkx==3.5
nibabel==5.3.2
nltk==3.9.1
notebook==6.5.7
notebook_shim==0.2.4
numba==0.60.0
numba-cuda==0.11.0
numexpr==2.14.1
numpy==2.0.2
nvidia-cublas-cu12==12.6.4.1
nvidia-cuda-cupti-cu12==12.6.80
nvidia-cuda-nvcc-cu12==12.5.82
nvidia-cuda-nvrtc-cu12==12.6.77
nvidia-cuda-runtime-cu12==12.6.77
nvidia-cudnn-cu12==9.10.2.21
nvidia-cufft-cu12==11.3.0.4
nvidia-cufile-cu12==1.11.1.6
nvidia-curand-cu12==10.3.7.77
nvidia-cusolver-cu12==11.7.1.2
nvidia-cusparse-cu12==12.5.4.2
nvidia-cusparselt-cu12==0.7.1
nvidia-ml-py==12.575.51
nvidia-nccl-cu12==2.27.3
nvidia-nvjitlink-cu12==12.6.85
nvidia-nvshmem-cu12==3.4.5
nvidia-nvtx-cu12==12.6.77
nvtx==0.2.13
nx-cugraph-cu12 @ https://pypi.nvidia.com/nx-cugraph-cu12/nx_cugraph_cu12-25.6.0-py3-none-any.whl
oauth2client==4.1.3
oauthlib==3.3.1
omegaconf==2.3.0
openai==1.109.1
opencv-contrib-python==4.12.0.88
opencv-python==4.12.0.88
opencv-python-headless==4.12.0.88
openpyxl==3.1.5
opentelemetry-api==1.37.0
opentelemetry-exporter-gcp-logging==1.10.0a0
opentelemetry-exporter-gcp-monitoring==1.10.0a0
opentelemetry-exporter-gcp-trace==1.10.0
opentelemetry-exporter-otlp-proto-common==1.37.0
opentelemetry-exporter-otlp-proto-http==1.37.0
opentelemetry-proto==1.37.0
opentelemetry-resourcedetector-gcp==1.10.0a0
opentelemetry-sdk==1.37.0
opentelemetry-semantic-conventions==0.58b0
opt_einsum==3.4.0
optax==0.2.6
optree==0.17.0
orbax-checkpoint==0.11.26
orjson==3.11.4
osqp==1.0.5
overrides==7.7.0
packaging==25.0
pandas==2.2.2
pandas-datareader==0.10.0
pandas-gbq==0.29.2
pandas-stubs==2.2.2.240909
pandocfilters==1.5.1
panel==1.8.2
param==2.2.1
parso==0.8.5
parsy==2.2
partd==1.4.2
patsy==1.0.2
peewee==3.18.2
peft==0.17.1
pexpect==4.9.0
pickleshare==0.7.5
pillow==11.3.0
platformdirs==4.5.0
plotly==5.24.1
plotnine==0.14.5
pluggy==1.6.0
plum-dispatch==2.5.8
ply==3.11
polars==1.25.2
pooch==1.8.2
portpicker==1.5.2
preshed==3.0.10
prettytable==3.16.0
proglog==0.1.12
progressbar2==4.5.0
prometheus_client==0.23.1
promise==2.3
prompt_toolkit==3.0.52
propcache==0.4.1
prophet==1.1.7
proto-plus==1.26.1
protobuf==5.29.5
psutil==5.9.5
psycopg2==2.9.11
psygnal==0.15.0
ptyprocess==0.7.0
py-cpuinfo==9.0.0
py4j==0.10.9.7
pyarrow==18.1.0
pyasn1==0.6.1
pyasn1_modules==0.4.2
pycairo==1.28.0
pycocotools==2.0.10
pycparser==2.23
pycryptodomex==3.23.0
pydantic==2.11.10
pydantic-settings==2.11.0
pydantic_core==2.33.2
pydata-google-auth==1.9.1
pydot==3.0.4
pydotplus==2.0.2
PyDrive2==1.21.3
pydub==0.25.1
pyerfa==2.0.1.5
pygame==2.6.1
pygit2==1.19.0
Pygments==2.19.2
PyGObject==3.42.0
PyJWT==2.10.1
pylibcudf-cu12 @ https://pypi.nvidia.com/pylibcudf-cu12/pylibcudf_cu12-25.6.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
pylibcugraph-cu12==25.6.0
pylibraft-cu12==25.6.0
pymc==5.26.1
pynndescent==0.5.13
pynvjitlink-cu12==0.7.0
pynvml==12.0.0
pyogrio==0.11.1
pyomo==6.9.5
PyOpenGL==3.1.10
pyOpenSSL==24.2.1
pyparsing==3.2.5
pyperclip==1.11.0
pyproj==3.7.2
pyproject_hooks==1.2.0
pyshp==3.0.2.post1
PySocks==1.7.1
pyspark==3.5.1
pytensor==2.35.1
pytest==8.4.2
python-apt==0.0.0
python-box==7.3.2
python-dateutil==2.9.0.post0
python-dotenv==1.1.1
python-json-logger==4.0.0
python-louvain==0.16
python-multipart==0.0.20
python-slugify==8.0.4
python-snappy==0.7.3
python-utils==3.9.1
pytz==2025.2
pyviz_comms==3.0.6
PyWavelets==1.9.0
PyYAML==6.0.3
pyzmq==26.2.1
raft-dask-cu12==25.6.0
rapids-dask-dependency==25.6.0
rapids-logger==0.1.19
ratelim==0.1.6
referencing==0.37.0
regex==2024.11.6
requests==2.32.4
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
requirements-parser==0.9.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rfc3987-syntax==1.1.0
rich==13.9.4
rmm-cu12==25.6.0
roman-numerals-py==3.1.0
rpds-py==0.28.0
rpy2==3.5.17
rsa==4.9.1
ruff==0.14.2
safehttpx==0.1.7
safetensors==0.6.2
scikit-image==0.25.2
scikit-learn==1.6.1
scipy==1.16.2
scooby==0.10.2
scs==3.2.9
seaborn==0.13.2
SecretStorage==3.4.0
semantic-version==2.10.0
Send2Trash==1.8.3
sentence-transformers==5.1.2
sentencepiece==0.2.1
sentry-sdk==2.42.1
setuptools==75.2.0
shap==0.49.1
shapely==2.1.2
shellingham==1.5.4
simple-parsing==0.1.7
simplejson==3.20.2
simsimd==6.5.3
six==1.17.0
sklearn-pandas==2.2.0
slicer==0.0.8
smart_open==7.4.1
smmap==5.0.2
sniffio==1.3.1
snowballstemmer==3.0.1
sortedcontainers==2.4.0
soundfile==0.13.1
soupsieve==2.8
soxr==1.0.0
spacy==3.8.7
spacy-legacy==3.0.12
spacy-loggers==1.0.5
spanner-graph-notebook==1.1.8
Sphinx==8.2.3
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
SQLAlchemy==2.0.44
sqlalchemy-spanner==1.17.1
sqlglot==25.20.2
sqlparse==0.5.3
srsly==2.5.1
sse-starlette==3.0.2
stanio==0.5.1
starlette==0.48.0
statsmodels==0.14.5
stringzilla==4.2.1
stumpy==1.13.0
sympy==1.13.3
tables==3.10.2
tabulate==0.9.0
tbb==2022.3.0
tblib==3.2.0
tcmlib==1.4.1
tenacity==8.5.0
tensorboard==2.19.0
tensorboard-data-server==0.7.2
tensorflow==2.19.0
tensorflow-datasets==4.9.9
tensorflow-hub==0.16.1
tensorflow-metadata==1.17.2
tensorflow-probability==0.25.0
tensorflow-text==2.19.0
tensorflow_decision_forests==1.12.0
tensorstore==0.1.78
termcolor==3.1.0
terminado==0.18.1
text-unidecode==1.3
textblob==0.19.0
tf-slim==1.1.0
tf_keras==2.19.0
thinc==8.3.6
threadpoolctl==3.6.0
tifffile==2025.10.16
tiktoken==0.12.0
timm==1.0.20
tinycss2==1.4.0
tokenizers==0.22.1
toml==0.10.2
tomlkit==0.13.3
toolz==0.12.1
torch==2.8.0+cu126
torchao==0.10.0
torchaudio==2.8.0+cu126
torchdata==0.11.0
torchsummary==1.5.1
torchtune==0.6.1
torchvision==0.23.0+cu126
tornado==6.5.1
tqdm==4.67.1
traitlets==5.7.1
traittypes==0.2.3
transformers==4.57.1
treelite==4.4.1
treescope==0.1.10
triton==3.4.0
tsfresh==0.21.1
tweepy==4.16.0
typeguard==4.4.4
typer==0.20.0
types-pytz==2025.2.0.20250809
types-setuptools==80.9.0.20250822
typing-inspection==0.4.2
typing_extensions==4.15.0
tzdata==2025.2
tzlocal==5.3.1
uc-micro-py==1.0.3
ucx-py-cu12==0.44.0
ucxx-cu12==0.44.0
umap-learn==0.5.9.post2
umf==1.0.2
uri-template==1.3.0
uritemplate==4.2.0
urllib3==2.5.0
uvicorn==0.38.0
vega-datasets==0.9.0
wadllib==1.3.6
wandb==0.22.2
wasabi==1.1.3
watchdog==6.0.0
wcwidth==0.2.14
weasel==0.4.1
webcolors==24.11.1
webencodings==0.5.1
websocket-client==1.9.0
websockets==15.0.1
Werkzeug==3.1.3
wheel==0.45.1
widgetsnbextension==3.6.10
wordcloud==1.9.4
wrapt==2.0.0
wurlitzer==3.1.1
xarray==2025.10.1
xarray-einstats==0.9.1
xgboost==3.1.1
xlrd==2.0.2
xxhash==3.6.0
xyzservices==2025.4.0
yarl==1.22.0
ydf==0.13.0
yellowbrick==1.5
yfinance==0.2.66
zict==3.0.0
zipp==3.23.0
zstandard==0.25.0